In [37]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import scipy.stats as stats
import statsmodels.api as sm
from scipy.stats import f_oneway
from scipy.stats import  chi2_contingency
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import files
upload = files.upload()

Saving Cutlets.csv to Cutlets.csv


In [ ]:
data = pd.read_csv("Cutlets.csv")

In [ ]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
unit_A = data["Unit A"]
unit_B = data["Unit B"]

In [ ]:
data.shape

(35, 2)

In [ ]:
data.var()# two units does not follow same variance

Unit A    0.083179
Unit B    0.117924
dtype: float64

In [ ]:
data.describe()

Unit A     Unit B
count  20.000000  20.000000
mean    7.088075   6.990615
std     0.299200   0.315005
min     6.534100   6.521700
25%     6.848500   6.760850
50%     7.120600   6.910450
75%     7.358900   7.211025
max     7.516900   7.545900

In [ ]:
p_value = stats.ttest_ind(unit_A,unit_B,equal_var=False)
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.47231324819145404)

In [ ]:
alpha=0.05

In [ ]:
if p_value[1] > alpha:
  print("Fail to Reject the null hypothesis cutlet have no significance difference in the diameter")
else:
    print("cutlet have  significance difference in the diameter")

Fail to Reject the null hypothesis cutlet have no significance difference in the diameter


Q2)

In [ ]:
from google.colab import files
upload = files.upload()

Saving LabTAT.csv to LabTAT.csv


In [ ]:
df = pd.read_csv("LabTAT.csv")

In [ ]:
df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [ ]:
df.isnull().sum()

Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [ ]:
df.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [ ]:
df.var()

Laboratory 1    173.543568
Laboratory 2    223.715251
Laboratory 3    273.539607
Laboratory 4    227.559632
dtype: float64

In [ ]:
p_value=f_oneway(df["Laboratory 1"],df["Laboratory 2"],df["Laboratory 3"],df["Laboratory 4"])

In [ ]:
if p_value[1] > 0.05 :
  print("fail to reject null hypothises no significant difference in the average TAT among the laboratories.")
else:
  print("significant difference in the average TAT among the laboratories.")

significant difference in the average TAT among the laboratories.


Q3)

In [3]:
from google.colab import files
upload = files.upload()

Saving BuyerRatio.csv to BuyerRatio.csv


In [4]:
data = pd.read_csv("BuyerRatio.csv")

In [7]:
data.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [27]:
df = data.iloc[:,1:]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   East    2 non-null      int64
 1   West    2 non-null      int64
 2   North   2 non-null      int64
 3   South   2 non-null      int64
dtypes: int64(4)
memory usage: 192.0 bytes


In [31]:
chi2,p,dof,expected_values=chi2_contingency(df)

In [32]:
chi2,p,dof,expected_values

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [33]:
if p <= 0.05:
  print("Not all proportion are equal (reject H0)")
else:
  print("All proportion are equal")

All proportion are equal


Q4)

In [34]:
from google.colab import files
upload = files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm.csv


In [53]:
data = pd.read_csv("Costomer+OrderForm.csv")

In [54]:
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [92]:
d4 = data["India"]
d3 = data["Malta"]
d2 = data["Indonesia"]
d1 = data["Phillippines"]



In [93]:
d1 = LabelEncoder().fit_transform(d1)

In [94]:
d2 = LabelEncoder().fit_transform(d2)

In [95]:
d3 = LabelEncoder().fit_transform(d3)

In [96]:
d4 = LabelEncoder().fit_transform(d4)

In [103]:
d1,d2,d3,d4


(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 

In [85]:
chi,p,dof,expect= chi2_contingency((d1,d2,d3,d4))

In [87]:
chi,p,dof,expect

(112.74730231885849,
 1.0,
 897,
 array([[0.74793008, 0.74793008, 0.49862006, ..., 0.74793008, 0.99724011,
         0.49862006],
        [0.73689052, 0.73689052, 0.49126035, ..., 0.73689052, 0.9825207 ,
         0.49126035],
        [0.7424103 , 0.7424103 , 0.4949402 , ..., 0.7424103 , 0.9898804 ,
         0.4949402 ],
        [0.77276909, 0.77276909, 0.51517939, ..., 0.77276909, 1.03035879,
         0.51517939]]))

In [88]:
if p <= 0.05:
  print("defective percentage is the same across all centers.")
else:
  print("The defective percentage varies across the centers.")

The defective percentage varies across the centers.
